### PR TITLE
Updating for EU

### PR DESCRIPTION
**Pull request by rshade**

### CODE REVIEW

**Comment by douglaswth** [comment]
Why not use the `rs_optima_host` keyword for this instead?

**Comment by rshade** [comment]
@douglaswth isn't the keyword to the old host and not `api.` one?

**Comment by douglaswth** [comment]
It is, but I believe it should be updated at some point. Anyway, the old one does forward to the same underlying API anyway.

**Comment by rshade** [comment]
Cool, I will fix it in the next rev :)

**Pull request merged**
